import type Colaborador from "../models/Colaborador";

export const Colaboradores: Colaborador[] = [
    {
        id: 2,
        nome: "Bianca Caetano",
        dataNascimento: new Date("1995-03-11"),
        cargo: "Gerente de RH",
        foto: "https://i.pravatar.cc/300?img=5",
        salario: 6500,
        dataAdimissao: new Date("2021-09-15"),
    },
    {
        id: 1,
        nome: "Ramon Silva",
        dataNascimento: new Date("1998-07-22"),
        cargo: "Analista de RH",
        foto: "https://i.pravatar.cc/300?img=12",
        salario: 4200,
        dataAdimissao: new Date("2023-02-01"),
    },
    {
        id: 3,
        nome: "Clarisse Rodrigues",
        dataNascimento: new Date("1997-01-05"),
        cargo: "Analista RH",
        foto: "https://i.pravatar.cc/300?img=9",
        salario: 4100,
        dataAdimissao: new Date("2022-08-10"),
    },
    {
        id: 4,
        nome: "Gabriela Almeida",
        dataNascimento: new Date("1996-11-30"),
        cargo: "Analista RH",
        foto: "https://i.pravatar.cc/300?img=32",
        salario: 4300,
        dataAdimissao: new Date("2022-05-18"),
    },
    {
        id: 5,
        nome: "Leonardo Botelho",
        dataNascimento: new Date("1994-04-14"),
        cargo: "Analista RH",
        foto: "https://i.pravatar.cc/300?img=8",
        salario: 4400,
        dataAdimissao: new Date("2020-10-21"),
    },
    {
        id: 6,
        nome: "Sabrina Novaes",
        dataNascimento: new Date("1999-12-09"),
        cargo: "Analista RH",
        foto: "https://i.pravatar.cc/300?img=47",
        salario: 4050,
        dataAdimissao: new Date("2024-01-08"),
    },
];