import type Colaborador from "../models/Colaborador";

export const Colaboradores: Colaborador[] = [
  {
    id: 1,
    nome: "Marina Falcão",
    email: "marina.falcao@rhmanager.com",
    telefone: "(11) 98765-4321",
    dataNascimento: new Date(`${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, "0")}-${String(new Date().getDate()).padStart(2, "0")}`),
    cargo: "Coordenadora de Pessoas",
    foto: "https://i.pravatar.cc/300?img=5",
    salario: 6500,
    dataAdimissao: new Date("2021-09-15"),
    status: "Ativo",
    endereco: {
      logradouro: "Rua das Flores",
      numero: "142",
      complemento: "Apto 31",
      bairro: "Jardim Paulista",
      cidade: "São Paulo",
      estado: "SP",
      cep: "01403-000",
    },
  },
  {
    id: 2,
    nome: "Thiago Martins",
    email: "thiago.martins@rhmanager.com",
    telefone: "(11) 97654-3210",
    dataNascimento: new Date("1998-07-22"),
    cargo: "Assistente de Recrutamento",
    foto: "https://i.pravatar.cc/300?img=12",
    salario: 4200,
    dataAdimissao: new Date("2023-02-01"),
    status: "Férias",
    ferias: {
      inicio: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() - 5),
      fim: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 25),
      diasConcedidos: 30,
    },
    endereco: {
      logradouro: "Av. Paulista",
      numero: "900",
      bairro: "Bela Vista",
      cidade: "São Paulo",
      estado: "SP",
      cep: "01310-100",
    },
  },
  {
    id: 3,
    nome: "Juliana Prado",
    email: "juliana.prado@rhmanager.com",
    telefone: "(21) 99876-5432",
    dataNascimento: new Date("1997-01-05"),
    cargo: "Especialista em Benefícios",
    foto: "https://i.pravatar.cc/300?img=9",
    salario: 4100,
    dataAdimissao: new Date("2022-08-10"),
    status: "Ativo",
    endereco: {
      logradouro: "Rua Visconde de Pirajá",
      numero: "550",
      complemento: "Sala 204",
      bairro: "Ipanema",
      cidade: "Rio de Janeiro",
      estado: "RJ",
      cep: "22410-002",
    },
  },
  {
    id: 4,
    nome: "Rafael Nunes",
    email: "rafael.nunes@rhmanager.com",
    telefone: "(31) 98765-1234",
    dataNascimento: new Date("1996-11-30"),
    cargo: "Analista de Treinamento",
    foto: "https://i.pravatar.cc/300?img=13",
    salario: 4300,
    dataAdimissao: new Date("2022-05-18"),
    status: "Afastado",
    endereco: {
      logradouro: "Rua da Bahia",
      numero: "1148",
      bairro: "Lourdes",
      cidade: "Belo Horizonte",
      estado: "MG",
      cep: "30160-011",
    },
  },
  {
    id: 5,
    nome: "Patrícia Azevedo",
    email: "patricia.azevedo@rhmanager.com",
    telefone: "(11) 96543-2109",
    dataNascimento: new Date("1994-04-14"),
    cargo: "Analista de Folha",
    foto: "https://i.pravatar.cc/300?img=32",
    salario: 4400,
    dataAdimissao: new Date("2020-10-21"),
    status: "Ativo",
    periodoConcessivoFim: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 45),
    endereco: {
      logradouro: "Alameda Santos",
      numero: "200",
      complemento: "Cobertura",
      bairro: "Cerqueira César",
      cidade: "São Paulo",
      estado: "SP",
      cep: "01419-000",
    },
  },
  {
    id: 6,
    nome: "Eduardo Barros",
    email: "eduardo.barros@rhmanager.com",
    telefone: "(41) 98877-6655",
    dataNascimento: new Date("1999-12-09"),
    cargo: "Auxiliar Administrativo",
    foto: "https://i.pravatar.cc/300?img=18",
    salario: 4050,
    dataAdimissao: new Date("2024-01-08"),
    status: "Ativo",
    endereco: {
      logradouro: "Rua XV de Novembro",
      numero: "700",
      bairro: "Centro",
      cidade: "Curitiba",
      estado: "PR",
      cep: "80020-310",
    },
  },
];
